name: Send GET Request Every 5 Minutes, Manually, and On Push

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:
  push:

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send GET Request
        run: |
          curl -X GET 'https://charlie-glass-admin-api.vercel.app/'
